import type { SidebarItem } from "./sidebar.types";
import {
  FiPieChart,
  FiShoppingCart,
  FiShoppingBag,
  FiBox,
  FiTool,
  FiBarChart2,
  FiSettings,
  FiMapPin,
  FiUsers,
  FiDatabase,
  FiDollarSign,
  FiClock,
} from "react-icons/fi";

export const sidebarItems: SidebarItem[] = [
  // 1. Dashboard — always visible to authenticated users
  {
    title: "Dashboard",
    icon: FiPieChart,
    path: "/dashboard",
  },
  // 2. Administration
  {
    title: "Administration",
    icon: FiSettings,
    path: "/company/view",
    pathsByPermission: [
      { permission: "company-settings.view", path: "/company/view" },
      { permission: "roles.view", path: "/roles" },
      { permission: "departments.view", path: "/departments" },
      { permission: "role-permissions.view", path: "/role-permissions" },
      { permission: "gst_tax.view", path: "/settings/gst-taxes" },
      { permission: "whatsapp.view", path: "/whatsapp" },
      { permission: "email-config.view", path: "/email-config" },
      { permission: "invoice-settings.view", path: "/settings/invoice" },
    ],
    activePaths: [
      "/company/view",
      "/settings/company",
      "/settings/gst-taxes",
      "/whatsapp",
      "/settings/invoice",
      "/roles",
      "/role-permissions",
      "/departments",
      "/users",
      "/permissions",
    ],
    permissionAny: [
      "company-settings.view",
      "roles.view",
      "departments.view",
      "role-permissions.view",
      "gst_tax.view",
      "whatsapp.view",
      "email-config.view",
      "invoice-settings.view",
    ],
  },
  // 3. HR & Organization
  {
    title: "HR & Organization",
    icon: FiUsers,
    path: "/machines",
    pathsByPermission: [
      { permission: "machines.view", path: "/machines" },
      { permission: "machine-assignments.view", path: "/machines/assignments" },
      { permission: "employees.view", path: "/employees" },
      { permission: "shifts.view", path: "/shifts" },
    ],
    activePaths: [
      "/employees",
      "/machines",
      "/machines/assignments",
      "/shifts",
    ],
    permissionAny: [
      "employees.view",
      "machines.view",
      "machine-assignments.view",
      "shifts.view",
    ],
  },
  // 4. Product Setup
  {
    title: "Product Setup",
    icon: FiDatabase,
    path: "/uoms",
    pathsByPermission: [
      { permission: "uoms.view", path: "/uoms" },
      { permission: "categories.view", path: "/categories" },
      { permission: "raw_material_categories.view", path: "/raw-material-categories" },
      { permission: "raw_materials.view", path: "/raw-materials" },
      { permission: "wastage-store.view", path: "/wastage-store" },
      { permission: "products.view", path: "/products" },
    ],
    activePaths: [
      "/products",
      "/categories",
      "/uoms",
      "/colours",
      "/sizes",
      "/raw-materials",
      "/raw-material-categories",
      "/wastage-store",
    ],
    permissionAny: [
      "products.view",
      "categories.view",
      "uoms.view",
      "raw_materials.view",
      "raw_material_categories.view",
      "wastage-store.view",
    ],
  },
  // 5. Purchase
  {
    title: "Purchase",
    icon: FiShoppingBag,
    path: "/suppliers",
    pathsByPermission: [
      { permission: "suppliers.view", path: "/suppliers" },
      { permission: "purchaseOrders.view", path: "/purchase-orders" },

      { permission: "invoice.view", path: "/invoice" },
      { permission: "expenses.view", path: "/expenses" },
      { permission: "purchase-returns.view", path: "/purchase-returns" },
    ],
    activePaths: [
      "/suppliers",
      "/purchase-orders",

      "/expenses",
      "/invoice",
      "/purchase-returns",
    ],
    permissionAny: [
      "suppliers.view",
      "purchaseOrders.view",

      "invoice.view",
      "expenses.view",
      "purchase-returns.view",
    ],
  },
  // 6. Sales
  {
    title: "Sales",
    icon: FiShoppingCart,
    path: "/customers",
    pathsByPermission: [
      { permission: "customers.view", path: "/customers" },
      { permission: "sales-orders.view", path: "/sales-order" },
      { permission: "draft-orders.view", path: "/draft-order" },
      { permission: "quotations.view", path: "/quatation-order" },
      { permission: "pending-quotations.view", path: "/pending-quotations" },
      { permission: "sales-invoices.view", path: "/sales-invoices" },
      { permission: "sales-returns.view", path: "/sales-returns" },
    ],
    activePaths: [
      "/customers",
      "/sales-order",
      "/draft-order",
      "/quatation-order",
      "/pending-quotations",
      "/sales-invoices",
      "/sales-returns",
    ],
    permissionAny: [
      "customers.view",
      "sales-orders.view",
      "draft-orders.view",
      "quotations.view",
      "pending-quotations.view",
      "sales-invoices.view",
      "sales-returns.view",
    ],
  },
  // 7. Production
  {
    title: "Production",
    icon: FiTool,
    path: "/allproduction-orders",
    pathsByPermission: [
      { permission: "production_orders.view", path: "/allproduction-orders" },
      { permission: "weekly_programs.view", path: "/weekly-machine-schedules" },
      { permission: "daily-machine-planning.view", path: "/daily-machine-planning" },
      { permission: "hourly_productions.view", path: "/hourly-work-reports" },
      { permission: "production-wastages.view", path: "/production-wastages" },
      { permission: "goods-dispatch.view", path: "/production/goods-dispatch" },
      { permission: "shift-execution.view", path: "/shift-execution" },
      { permission: "oee-dashboard.view", path: "/oee-dashboard" },
      { permission: "sales_products.view", path: "/sales-products" },
    ],
    activePaths: [
      "/approved-sales-orders",
      "/production-orders",
      "/allproduction-orders",
      "/weekly-machine-schedules",
      "/daily-machine-planning",
      "/hourly-work-reports",
      "/production-wastages",
      "/oee-dashboard",
      "/shift-execution",
      "/production-dashboard",
      "/sales-products",
      "/production/goods-dispatch",
    ],
    permissionAny: [
      "production_orders.view",
      "weekly_programs.view",
      "daily-machine-planning.view",
      "hourly_productions.view",
      "production-wastages.view",
      "goods-dispatch.view",
      "shift-execution.view",
      "oee-dashboard.view",
      "sales_products.view",
    ],
  },
  // 8. Inventory
  {
    title: "Inventory",
    icon: FiBox,
    path: "/stock",
    pathsByPermission: [
      { permission: "raw_material_stocks.view", path: "/stock" },
      { permission: "finished_goods_stocks.view", path: "/finished-stock" },
      { permission: "wastage-stock.view", path: "/wastage-stock" },
      { permission: "stock-adjustments.view", path: "/inventory/stock-adjustments" },
      { permission: "eod-stock.view", path: "/inventory/eod-stock" },
    ],
    activePaths: [
      "/stock",
      "/inventory/stock-adjustments",
      "/inventory/eod-stock",
      "/finished-stock",
      "/wastage-stock",
    ],
    permissionAny: [
      "raw_material_stocks.view",
      "finished_goods_stocks.view",
      "wastage-stock.view",
      "stock-adjustments.view",
      "eod-stock.view",
    ],
  },
  // 9. Store & Locations
  {
    title: "Store & Locations",
    icon: FiMapPin,
    path: "/storage-stores",
    pathsByPermission: [
      { permission: "stores.view", path: "/storage-stores" },
      { permission: "store-types.view", path: "/store-types" },
      { permission: "locations.view", path: "/locations" },
    ],
    activePaths: ["/storage-stores", "/store-types", "/locations"],
    permissionAny: ["stores.view", "store-types.view", "locations.view"],
  },

  // 10. Accounts
  {
    title: "Accounts",
    icon: FiDollarSign,
    path: "/accounts/payable",
    pathsByPermission: [
      { permission: "payable.view", path: "/accounts/payable" },
      { permission: "receivable.view", path: "/accounts/receivable" },
      { permission: "accounts.view", path: "/accounts" },
      { permission: "vouchers.view", path: "/accounts/vouchers" },
      { permission: "petty-cash.view", path: "/accounts/petty-cash" },
      { permission: "chart-of-accounts.view", path: "/accounts/chart-of-accounts" },
    ],
    activePaths: [
      "/accounts/payable",
      "/accounts/receivable",
      "/accounts/ledger-statement",
      "/accounts/chart-of-accounts",
      "/accounts/vouchers",
      "/accounts/sales-returns",
      "/accounts/purchase-returns",
      "/accounts/petty-cash",
    ],
    permissionAny: [
      "accounts.view",
      "payable.view",
      "receivable.view",
      "vouchers.view",
      "petty-cash.view",
      "chart-of-accounts.view",
    ],
  },
  // 11. Payroll
  {
    title: "Payroll",
    icon: FiClock,
    path: "/payroll",
    pathsByPermission: [
      { permission: "payroll.view", path: "/payroll" },
      { permission: "payroll-run.view", path: "/payroll/run" },
      { permission: "payroll-settings.view", path: "/payroll/settings" },
      { permission: "payroll-attendance.view", path: "/payroll/attendance" },
      { permission: "payroll-advance.view", path: "/payroll/advance" },
    ],
    activePaths: [
      "/payroll",
      "/payroll/run",
      "/payroll/settings",
      "/payroll/weekly-report",
      "/payroll/monthly-report",
    ],
    permissionAny: [
      "payroll.view",
      "payroll-run.view",
      "payroll-settings.view",
      "payroll-attendance.view",
      "payroll-advance.view",
    ],
  },
  // 12. Reports
  {
    title: "Reports",
    icon: FiBarChart2,
    path: "/reports/sales",
    pathsByPermission: [
      { permission: "sales-reports.view", path: "/reports/sales" },
      { permission: "purchase-reports.view", path: "/reports/purchase" },
      { permission: "inventory-reports.view", path: "/reports/inventory" },
      { permission: "production-reports.view", path: "/reports/production" },
      { permission: "audit-reports.view", path: "/reports/audit" },
    ],
    activePaths: [
      "/reports/sales",
      "/reports/purchase",
      "/reports/inventory",
      "/reports/production",
      "/reports/audit",
    ],
    permissionAny: [
      "sales-reports.view",
      "purchase-reports.view",
      "inventory-reports.view",
      "production-reports.view",
      "audit-reports.view",
    ],
  },
];
